In [45]:
from numpy import array
from numpy import argmax
from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import OneHotEncoder
import re
import pandas as pd


def one_hot_encoding(sequence):
    seq_array = array(list(sequence))
    label_encoder = LabelEncoder()
    integer_encoded_seq = label_encoder.fit_transform(seq_array)
    onehot_encoder = OneHotEncoder(sparse=False)
    integer_encoded_seq = integer_encoded_seq.reshape(len(integer_encoded_seq), 1)
    onehot_encoded_seq = onehot_encoder.fit_transform(integer_encoded_seq)
    return onehot_encoded_seq

In [47]:
sequence1 = "ATGTGTCGTAGTCGTACG"
sequence2 = "ATGTTTTGTAGTTATCGTACG"

df1 = pd.DataFrame(one_hot_encoding(sequence))
df2 = pd.DataFrame(one_hot_encoding(sequence))

pd.concat([df1, df2], axis=1, ignore_index=True)

      0    1    2    3    4    5    6    7
0   1.0  0.0  0.0  0.0  1.0  0.0  0.0  0.0
1   0.0  0.0  0.0  1.0  0.0  0.0  0.0  1.0
2   0.0  0.0  1.0  0.0  0.0  0.0  1.0  0.0
3   0.0  0.0  0.0  1.0  0.0  0.0  0.0  1.0
4   0.0  0.0  1.0  0.0  0.0  0.0  1.0  0.0
5   0.0  0.0  0.0  1.0  0.0  0.0  0.0  1.0
6   0.0  1.0  0.0  0.0  0.0  1.0  0.0  0.0
7   0.0  0.0  1.0  0.0  0.0  0.0  1.0  0.0
8   0.0  0.0  0.0  1.0  0.0  0.0  0.0  1.0
9   1.0  0.0  0.0  0.0  1.0  0.0  0.0  0.0
10  0.0  0.0  1.0  0.0  0.0  0.0  1.0  0.0
11  0.0  0.0  0.0  1.0  0.0  0.0  0.0  1.0
12  0.0  1.0  0.0  0.0  0.0  1.0  0.0  0.0
13  0.0  0.0  1.0  0.0  0.0  0.0  1.0  0.0
14  0.0  0.0  0.0  1.0  0.0  0.0  0.0  1.0
15  1.0  0.0  0.0  0.0  1.0  0.0  0.0  0.0
16  0.0  1.0  0.0  0.0  0.0  1.0  0.0  0.0
17  0.0  0.0  1.0  0.0  0.0  0.0  1.0  0.0

In [10]:
import numpy as np

seqs = ["ACGTCCA","CGGATTG"]

CHARS = 'ACGT'
CHARS_COUNT = len(CHARS)

maxlen = max(map(len, seqs))
res = np.zeros((len(seqs), CHARS_COUNT * maxlen), dtype=np.uint8)

for si, seq in enumerate(seqs):
    seqlen = len(seq)
    arr = np.chararray((seqlen,), buffer=seq)
    for ii, char in enumerate(CHARS):
        res[si][ii*seqlen:(ii+1)*seqlen][arr == char] = 1

print(res)

[[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]]